name=ArucoLite
version=2.0.3
author=Paulo Marques
maintainer=Paulo Marques
sentence=Lightweight ArUco tracking
paragraph=Needs about 30kB to process a 324x324 image, takes about 25~30ms on a RP2040
category=Data Processing
url=https://github.com/pmarques-dev/ArucoLite
architectures=*
includes=ArucoLite.h
